apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeinstana-operator
  labels:
    role: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beeinstana-operator
  template:
    metadata:
      labels:
        name: beeinstana-operator
    spec:
      serviceAccountName: beeinstana-operator
      imagePullSecrets:
        - name: instana-registry
      containers:
        - name: beeinstana-operator
          image: containers.instana.io/release/product/beeinstana/operator:1.0.51
          imagePullPolicy: Always
          command:
            - /manager
          args:
            - --enable-leader-election
            - --namespace=$(OPERATOR_NAMESPACE)
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
