apiVersion: v1
kind: ServiceAccount
metadata:
  name: beeinstana-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beeinstana-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx-admission
  labels:
    app.kubernetes.io/name: ingress-nginx
